# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94034ecfb5a1e3347267519c8efbb949d1825a08116f573ead842adbcd54977ee62d656d4968365e12d19678f29a385436854d0d1c103aaa1041f24112a87e54

test:
  secret_key_base: fa0562ad0e6b6d9d358966eb74fb91872fff7f2f3c7889f0697ae835cf7aca4857e94a5c8d7c2d90814c028bbebebec456b5fdb5ab2be4ff69c66ce68e5c4b40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
